Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -21,6 +21,13 @@ jobs:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'  # Caches npm dependencies
 
+      - name: Check for package-lock.json or yarn.lock
+        run: |
+          if [ ! -f package-lock.json ] && [ ! -f yarn.lock ]; then
+            echo "Error: Dependencies lock file is not found. Exiting."
+            exit 1
+          fi
+
       - name: Install dependencies
         run: npm ci  # This command uses package-lock.json if present
 
